import Navbar from "@/pages/Navbar";
import "./globals.css";
// import Fotter from "@/pages/Footer";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        {/* <Fotter/> */}
      </body>
    </html>
  );
}
